// Generated by svd2swift.

import MMIO

/// DMA controller
let dma1 = DMA1(unsafeAddress: 0x40026000)

/// General-purpose I/Os
let gpioa = GPIOA(unsafeAddress: 0x40020000)

/// General-purpose I/Os
let gpiob = GPIOB(unsafeAddress: 0x40020400)

/// General-purpose I/Os
let gpioi = GPIOI(unsafeAddress: 0x40022000)

/// Reset and clock control
let rcc = RCC(unsafeAddress: 0x40023800)

/// Serial peripheral interface
let spi2 = SPI2(unsafeAddress: 0x40003800)

/// Universal synchronous asynchronous receiver transmitter
let usart1 = USART1(unsafeAddress: 0x40011000)
