// Generated by svd2swift.

import MMIO

/// FLASH
let flash = FLASH(unsafeAddress: 0x40023c00)

/// General-purpose I/Os
let gpioa = GPIOA(unsafeAddress: 0x40020000)

/// General-purpose I/Os
let gpiob = GPIOB(unsafeAddress: 0x40020400)

/// General-purpose I/Os
let gpioc = GPIOC(unsafeAddress: 0x40020800)

/// General-purpose I/Os
let gpiod = GPIOD(unsafeAddress: 0x40020c00)

/// General-purpose I/Os
let gpioe = GPIOE(unsafeAddress: 0x40021000)

/// General-purpose I/Os
let gpiof = GPIOF(unsafeAddress: 0x40021400)

/// General-purpose I/Os
let gpiog = GPIOG(unsafeAddress: 0x40021800)

/// General-purpose I/Os
let gpioh = GPIOH(unsafeAddress: 0x40021c00)

/// General-purpose I/Os
let gpioi = GPIOI(unsafeAddress: 0x40022000)

/// General-purpose I/Os
let gpioj = GPIOJ(unsafeAddress: 0x40022400)

/// General-purpose I/Os
let gpiok = GPIOK(unsafeAddress: 0x40022800)

/// LCD-TFT Controller
let ltdc = LTDC(unsafeAddress: 0x40016800)

/// Reset and clock control
let rcc = RCC(unsafeAddress: 0x40023800)
