name: 'Install Swift'
description: 'Installs the Swift specified by a .swift-version file'

runs:
  using: "composite"
  steps:
    - name: Install apt dependencies
      shell: bash
      run: |
        SUDO=$(if [[ $EUID -ne 0 ]]; then echo sudo; fi)
        $SUDO apt-get -qq update
        $SUDO apt-get -qq -y install curl gpg binutils git unzip gnupg2 \
          libc6-dev libcurl4-openssl-dev libedit2 libgcc-13-dev libpython3-dev \
          libstdc++-13-dev libxml2-dev libncurses-dev libz3-dev pkg-config \
          tzdata zlib1g-dev
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Swiftly
      shell: bash
      run: |
        UNAME=$(uname -m)
        curl -O "https://download.swift.org/swiftly/linux/swiftly-$UNAME.tar.gz"
        tar zxf "swiftly-$UNAME.tar.gz"
        ./swiftly init --skip-install --assume-yes --quiet-shell-followup

        export SWIFTLY_HOME_DIR="$HOME/.local/share/swiftly"
        echo "SWIFTLY_HOME_DIR=$SWIFTLY_HOME_DIR" >> $GITHUB_ENV
        echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> ~/.bashrc

        export SWIFTLY_BIN_DIR="$HOME/.local/share/swiftly/bin"
        echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> $GITHUB_ENV
        echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> ~/.bashrc

        export PATH="$SWIFTLY_BIN_DIR:$PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "PATH=$SWIFTLY_BIN_DIR:$PATH" >> ~/.bashrc

    - name: Install Swift
      shell: bash
      run: |
        swiftly install
        swift --version
