name: 'Install Swift'
description: 'Installs the Swift specified by a .swift-version file'

runs:
  using: "composite"
  steps:
    - name: Install apt dependencies
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq -y install curl gpg binutils git unzip gnupg2 libc6-dev \
          libcurl4-openssl-dev libedit2 libgcc-13-dev libpython3-dev \
          libstdc++-13-dev libxml2-dev libncurses-dev libz3-dev pkg-config \
          tzdata zlib1g-dev
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Swiftly
      shell: bash
      run: |
        curl -O "https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz"
        tar zxf "swiftly-$(uname -m).tar.gz"
        ./swiftly init --skip-install --assume-yes --quiet-shell-followup

        export SWIFTLY_HOME_DIR="$HOME/.local/share/swiftly"
        echo "SWIFTLY_HOME_DIR=$SWIFTLY_HOME_DIR" >> $GITHUB_ENV
        
        export SWIFTLY_BIN_DIR="$HOME/.local/share/swiftly/bin"
        echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> $GITHUB_ENV

        export PATH="$SWIFTLY_BIN_DIR:$PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: Install Swift
      shell: bash
      run: |
        swiftly install
        swift --version
