// Generated by svd2swift.

import MMIO

/// General-purpose I/Os
public let gpioa = GPIOA(unsafeAddress: 0x40020000)

/// General-purpose I/Os
public let gpiob = GPIOB(unsafeAddress: 0x40020400)

/// Reset and clock control
public let rcc = RCC(unsafeAddress: 0x40023800)

/// Universal synchronous asynchronous receiver transmitter
public let usart1 = USART1(unsafeAddress: 0x40011000)
