// Generated by svd2swift.

import MMIO

/// DMA controller
public let dma1 = DMA1(unsafeAddress: 0x40026000)

/// DMA controller
public let dma2 = DMA2(unsafeAddress: 0x40026400)

/// General-purpose I/Os
public let gpioa = GPIOA(unsafeAddress: 0x40020000)

/// General-purpose I/Os
public let gpiob = GPIOB(unsafeAddress: 0x40020400)

/// General-purpose I/Os
public let gpioi = GPIOI(unsafeAddress: 0x40022000)

/// Reset and clock control
public let rcc = RCC(unsafeAddress: 0x40023800)

/// Serial peripheral interface
public let spi1 = SPI1(unsafeAddress: 0x40013000)

/// Serial peripheral interface
public let spi2 = SPI2(unsafeAddress: 0x40003800)

/// Universal synchronous asynchronous receiver transmitter
public let usart1 = USART1(unsafeAddress: 0x40011000)
