// Generated by svd2swift.

import MMIO

/// Nested Vectored Interrupt Controller
@RegisterBlock
public struct NVIC {
    /// Interrupt Set-Enable Register
    @RegisterBlock(offset: 0x0)
    public var iser0: Register<ISER0>

    /// Interrupt Set-Enable Register
    @RegisterBlock(offset: 0x4)
    public var iser1: Register<ISER1>

    /// Interrupt Set-Enable Register
    @RegisterBlock(offset: 0x8)
    public var iser2: Register<ISER2>

    /// Interrupt Clear-Enable Register
    @RegisterBlock(offset: 0x80)
    public var icer0: Register<ICER0>

    /// Interrupt Clear-Enable Register
    @RegisterBlock(offset: 0x84)
    public var icer1: Register<ICER1>

    /// Interrupt Clear-Enable Register
    @RegisterBlock(offset: 0x88)
    public var icer2: Register<ICER2>

    /// Interrupt Set-Pending Register
    @RegisterBlock(offset: 0x100)
    public var ispr0: Register<ISPR0>

    /// Interrupt Set-Pending Register
    @RegisterBlock(offset: 0x104)
    public var ispr1: Register<ISPR1>

    /// Interrupt Set-Pending Register
    @RegisterBlock(offset: 0x108)
    public var ispr2: Register<ISPR2>

    /// Interrupt Clear-Pending Register
    @RegisterBlock(offset: 0x180)
    public var icpr0: Register<ICPR0>

    /// Interrupt Clear-Pending Register
    @RegisterBlock(offset: 0x184)
    public var icpr1: Register<ICPR1>

    /// Interrupt Clear-Pending Register
    @RegisterBlock(offset: 0x188)
    public var icpr2: Register<ICPR2>

    /// Interrupt Active Bit Register
    @RegisterBlock(offset: 0x200)
    public var iabr0: Register<IABR0>

    /// Interrupt Active Bit Register
    @RegisterBlock(offset: 0x204)
    public var iabr1: Register<IABR1>

    /// Interrupt Active Bit Register
    @RegisterBlock(offset: 0x208)
    public var iabr2: Register<IABR2>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x300)
    public var ipr0: Register<IPR0>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x304)
    public var ipr1: Register<IPR1>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x308)
    public var ipr2: Register<IPR2>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x30c)
    public var ipr3: Register<IPR3>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x310)
    public var ipr4: Register<IPR4>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x314)
    public var ipr5: Register<IPR5>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x318)
    public var ipr6: Register<IPR6>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x31c)
    public var ipr7: Register<IPR7>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x320)
    public var ipr8: Register<IPR8>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x324)
    public var ipr9: Register<IPR9>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x328)
    public var ipr10: Register<IPR10>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x32c)
    public var ipr11: Register<IPR11>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x330)
    public var ipr12: Register<IPR12>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x334)
    public var ipr13: Register<IPR13>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x338)
    public var ipr14: Register<IPR14>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x33c)
    public var ipr15: Register<IPR15>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x340)
    public var ipr16: Register<IPR16>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x344)
    public var ipr17: Register<IPR17>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x348)
    public var ipr18: Register<IPR18>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x34c)
    public var ipr19: Register<IPR19>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x350)
    public var ipr20: Register<IPR20>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x354)
    public var ipr21: Register<IPR21>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x358)
    public var ipr22: Register<IPR22>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x35c)
    public var ipr23: Register<IPR23>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x360)
    public var ipr24: Register<IPR24>

    /// Interrupt Priority Register
    @RegisterBlock(offset: 0x364)
    public var ipr25: Register<IPR25>
}

extension NVIC {
    /// Interrupt Set-Enable Register
    @Register(bitWidth: 32)
    public struct ISER0 {
        /// SETENA
        @ReadWrite(bits: 0..<32)
        public var setena: SETENA
    }

    /// Interrupt Set-Enable Register
    @Register(bitWidth: 32)
    public struct ISER1 {
        /// SETENA
        @ReadWrite(bits: 0..<32)
        public var setena: SETENA
    }

    /// Interrupt Set-Enable Register
    @Register(bitWidth: 32)
    public struct ISER2 {
        /// SETENA
        @ReadWrite(bits: 0..<32)
        public var setena: SETENA
    }

    /// Interrupt Clear-Enable Register
    @Register(bitWidth: 32)
    public struct ICER0 {
        /// CLRENA
        @ReadWrite(bits: 0..<32)
        public var clrena: CLRENA
    }

    /// Interrupt Clear-Enable Register
    @Register(bitWidth: 32)
    public struct ICER1 {
        /// CLRENA
        @ReadWrite(bits: 0..<32)
        public var clrena: CLRENA
    }

    /// Interrupt Clear-Enable Register
    @Register(bitWidth: 32)
    public struct ICER2 {
        /// CLRENA
        @ReadWrite(bits: 0..<32)
        public var clrena: CLRENA
    }

    /// Interrupt Set-Pending Register
    @Register(bitWidth: 32)
    public struct ISPR0 {
        /// SETPEND
        @ReadWrite(bits: 0..<32)
        public var setpend: SETPEND
    }

    /// Interrupt Set-Pending Register
    @Register(bitWidth: 32)
    public struct ISPR1 {
        /// SETPEND
        @ReadWrite(bits: 0..<32)
        public var setpend: SETPEND
    }

    /// Interrupt Set-Pending Register
    @Register(bitWidth: 32)
    public struct ISPR2 {
        /// SETPEND
        @ReadWrite(bits: 0..<32)
        public var setpend: SETPEND
    }

    /// Interrupt Clear-Pending Register
    @Register(bitWidth: 32)
    public struct ICPR0 {
        /// CLRPEND
        @ReadWrite(bits: 0..<32)
        public var clrpend: CLRPEND
    }

    /// Interrupt Clear-Pending Register
    @Register(bitWidth: 32)
    public struct ICPR1 {
        /// CLRPEND
        @ReadWrite(bits: 0..<32)
        public var clrpend: CLRPEND
    }

    /// Interrupt Clear-Pending Register
    @Register(bitWidth: 32)
    public struct ICPR2 {
        /// CLRPEND
        @ReadWrite(bits: 0..<32)
        public var clrpend: CLRPEND
    }

    /// Interrupt Active Bit Register
    @Register(bitWidth: 32)
    public struct IABR0 {
        /// ACTIVE
        @ReadOnly(bits: 0..<32)
        public var active: ACTIVE
    }

    /// Interrupt Active Bit Register
    @Register(bitWidth: 32)
    public struct IABR1 {
        /// ACTIVE
        @ReadOnly(bits: 0..<32)
        public var active: ACTIVE
    }

    /// Interrupt Active Bit Register
    @Register(bitWidth: 32)
    public struct IABR2 {
        /// ACTIVE
        @ReadOnly(bits: 0..<32)
        public var active: ACTIVE
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR0 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR1 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR2 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR3 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR4 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR5 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR6 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR7 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR8 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR9 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR10 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR11 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR12 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR13 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR14 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR15 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR16 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR17 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR18 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR19 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR20 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR21 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR22 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR23 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR24 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }

    /// Interrupt Priority Register
    @Register(bitWidth: 32)
    public struct IPR25 {
        /// IPR_N0
        @ReadWrite(bits: 0..<8)
        public var ipr_n0: IPR_N0

        /// IPR_N1
        @ReadWrite(bits: 8..<16)
        public var ipr_n1: IPR_N1

        /// IPR_N2
        @ReadWrite(bits: 16..<24)
        public var ipr_n2: IPR_N2

        /// IPR_N3
        @ReadWrite(bits: 24..<32)
        public var ipr_n3: IPR_N3
    }
}
