name: Build Raspberry Pi Baremetal Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # Build on Mondays at 9am PST every week
    - cron:  '0 17 * * 1'
jobs:
  build-rpi-baremetal:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        example: [rpi5-blink, rpi4b-blink]
        swift: [swift-DEVELOPMENT-SNAPSHOT-2024-12-04-a]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: sudo apt-get -qq update && sudo apt-get -qq -y install make llvm
        
      - name: Build ${{ matrix.example }}
        run: |
          cd ${{ matrix.example }}
          make
