name: Build Raspberry Pi Baremetal Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # Build on Mondays at 9am PST every week
    - cron: '0 17 * * 1'

jobs:
  build-rpi-baremetal:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        example: [rpi4b-blink, rpi5-blink]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: sudo apt-get -qq update && sudo apt-get -qq -y install make llvm

      - name: Install Swift
        uses: ./.github/actions/install-swift

      - name: Build ${{ matrix.example }}
        working-directory: ${{ matrix.example }}
        run: make


